---
#
# Gather facts from all machines in the cluster
#
# This is required even if you're just running against one specific
# machine in the cluster because the configuration files need host
# information for all nodes in the cluster when writing the config
# files for various services Humio uses.
#
- hosts: all
  become: true
  serial: 10
  pre_tasks:
    - name: Gather facts from ALL hosts (regardless of limit or tags)
      tags: always
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      when: hostvars[item]['ansible_' + humio_network_interface] is not defined
      with_items: "{{ groups['all'] }}"

############################################
#
# Install Java + Humio roles on humio hosts
#
- hosts: humios
  tags: humio
  serial: 1
  become: true
  tasks:
    - name: Include Humio server role
      import_role: 
        name: humio.server
        tasks_from: humio-update
  # include_role: 
  #   name: humio.server
  #   apply:
  #     tags: humio-update
  #   zookeeper_hosts: "
  #     {%- set ips = [] %}
  #     {%- for host in groups['zookeepers'] %}
  #     {{- ips.append(dict(id=hostvars[host]['cluster_index'], host=host, ip=hostvars[host]['ansible_' + humio_network_interface].ipv4.address)) }}
  #     {%- endfor %}
  #     {{- ips -}}"
  #   kafka_hosts: "
  #     {%- set ips = [] %}
  #     {%- for host in groups['kafkas'] %}
  #     {{- ips.append(dict(id=hostvars[host]['cluster_index'], host=host, ip=hostvars[host]['ansible_' + humio_network_interface].ipv4.address)) }}
  #     {%- endfor %}
  #     {{- ips -}}"
  #   humio_host_id: "{{ cluster_index }}"
  #   humio_config:
  #     "0": "EXTERNAL_URL=http://{{ hostvars[inventory_hostname]['ansible_' + humio_network_interface].ipv4.address }}:8080"
  #     "1": "EXTERNAL_URL=http://{{ hostvars[inventory_hostname]['ansible_' + humio_network_interface].ipv4.address }}:8081"
